// generated by nuxt-og-image
import type { ModuleOptions } from 'nuxt-og-image'
declare module '#nuxt-og-image/config' {
  export const forcePrerender: false | ModuleOptions['forcePrerender']
  export const host: "https://docs.vuestorefront.io" | ModuleOptions['host']
  export const defaults: {"component":"OgImage","width":1200,"height":630} | ModuleOptions['defaults']
  export const satoriProvider: true | ModuleOptions['satoriProvider']
  export const browserProvider: true | ModuleOptions['browserProvider']
  export const fonts: ["Inter:400","Inter:700"] | ModuleOptions['fonts']
  export const satoriOptions: {} | ModuleOptions['satoriOptions']
  export const experimentalInlineWasm: false | ModuleOptions['experimentalInlineWasm']
  export const experimentalRuntimeBrowser: false | ModuleOptions['experimentalRuntimeBrowser']
  export const playground: true | ModuleOptions['playground']
  export const assetDirs: ["/Users/richardrohrig/m2/nuxt3-magento-sdk-storefront/apps/docs/public","/Users/richardrohrig/m2/nuxt3-magento-sdk-storefront/node_modules/nuxt-og-image/dist/runtime/public-assets"] | ModuleOptions['assetDirs']
}
