// generated by nuxt-simple-robots
import type { ModuleOptions } from 'nuxt-simple-robots'
declare module '#nuxt-simple-robots/config' {
  export const enabled: true | ModuleOptions['enabled']
  export const host: "https://docs.vuestorefront.io" | ModuleOptions['host']
  export const disallow: [] | ModuleOptions['disallow']
  export const sitemap: ["https://docs.vuestorefront.io/sitemap.xml"] | ModuleOptions['sitemap']
  export const indexable: false | ModuleOptions['indexable']
  export const robotsEnabledValue: "index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1" | ModuleOptions['robotsEnabledValue']
  export const robotsDisabledValue: "noindex, nofollow" | ModuleOptions['robotsDisabledValue']
}
