// generated by nuxt-seo-kit
import type { ModuleOptions } from 'nuxt-seo-kit'
declare module '#nuxt-seo-kit/config' {
  export const splash: true | ModuleOptions['splash']
  export const siteName: "Vue Storefront Docs" | ModuleOptions['siteName']
  export const siteDescription: "Frontend as a Service for Composable Commerce" | ModuleOptions['siteDescription']
  export const siteImage: undefined | ModuleOptions['siteImage']
  export const siteUrl: "https://docs.vuestorefront.io" | ModuleOptions['siteUrl']
  export const titleSeparator: "|" | ModuleOptions['titleSeparator']
  export const trailingSlash: false | ModuleOptions['trailingSlash']
  export const language: "en" | ModuleOptions['language']
  export const indexable: false | ModuleOptions['indexable']
}
