// generated by nuxt-simple-sitemap
import type { ModuleOptions } from 'nuxt-simple-sitemap'
declare module '#nuxt-simple-sitemap/config' {
  export const include: ["/**"] | ModuleOptions['include']
  export const hostname: "https://docs.vuestorefront.io" | ModuleOptions['hostname']
  export const trailingSlash: false | ModuleOptions['trailingSlash']
  export const enabled: true | ModuleOptions['enabled']
  export const urls: [] | ModuleOptions['urls']
  export const defaults: {} | ModuleOptions['defaults']
  export const devPreview: true | ModuleOptions['devPreview']
  export const inferStaticPagesAsRoutes: true | ModuleOptions['inferStaticPagesAsRoutes']
}
