// Generated by nuxt-simple-sitemap
import type { SitemapItemLoose } from 'sitemap'

type SitemapEntry = SitemapItemLoose & {
  changefreq?: 'always' | 'hourly' | 'daily' | 'weekly' | 'monthly' | 'yearly' | 'never' | (string & Record<never, never>)
}

interface NuxtSimpleSitemapNitroRules {
  index?: boolean
  sitemap?: SitemapEntry
}
declare module 'nitropack' {
  interface NitroRouteRules extends NuxtSimpleSitemapNitroRules {}
  interface NitroRouteConfig extends NuxtSimpleSitemapNitroRules {}
}
export {}
